vivo=input("write a number")
print(vivo,type(vivo))
vivo1=int(vivo)
print(vivo1,type(vivo1))
vivo2=list(vivo)
print(vivo2,type(vivo2))
vivo3=tuple(vivo)
print(vivo3,type(vivo3))
vivo4=float(vivo)
print(vivo4,type(vivo4))