opo=input("write a number")
print(opo,type(opo))
opo1=int(opo)
print(opo1,type(opo1))
opo2=list(opo)
print(opo2,type(opo2))
opo3=tuple(opo)
print(opo3,type(opo3))
opo4=float(opo)
print(opo4,type(opo4))
