number=input("enter a number")
print(number,type(number))
number1=int(number)
print(number1,type(number1))
number2=list(number)
print(number2,type(number2))
number3=tuple(number)
print(number3,type(number3))
number4=float(number)
print(number4,type(number4))